### PR TITLE
Chunk - Add optimised traverse_ for StackSafeMonad.

### PR DESCRIPTION
**Pull request by diesalbla**
If our Applicative F is actually an instance of `StackSafeMonad`, we can avoid the default implementation of traverse_, which is based on a `foldRight` method of Foldable and has to allocate a set of `Eval` objects. Instead, we can just loop on the monad itself.

_Note_ Given that in practice Streams are mostly used with IO-like datatypes which are stack-safe, this should have some impact.

### CODE REVIEW

**Comment by armanbilge** [comment]
Linking to:
- https://github.com/typelevel/cats/issues/4408

Actually, if we made this optimization in Cats, we probably wouldn't need to repeat it here?

**Comment by diesalbla** [comment]
> Actually, if we made this optimization in Cats, we probably wouldn't need to repeat it here?

As it happens I was taking a look at the `cats` implementation, but the `Foldable` type class seems to provide little. With `Chunk` we can optimise it right away.

**Comment by armanbilge** [comment]
> Note that the ticket refers to the `traverse` method, not the procedural `traverse_`

Yes indeed, but we can make the described optimizations for both `traverse` and `traverse_` upstream in Cats.

**Comment by diesalbla** [comment]
> Yes indeed, but we can make the described optimizations for both traverse and traverse_ upstream in Cats.

It may take a while for those to get released, if and when they are done (the link is to an issue). This PR is ready as of now.

**Comment by armanbilge** [comment]
Sorry, I didn't mean it as a blocker here 🙂 rather, to further justify landing these changes in Cats.

**Pull request merged**
