### PR TITLE
Fix UnixSockets classpath detection logic

### LINKED ISSUE #2623: UnixSockets throws a NoClassDefFoundError when used on JDK15 or prior
When using the Scala 3 artifact of fs2-io along with JDK15 or prior, any use of `UnixSockets` results in a `NoClassDefFoundError`: 

```scala
@ fs2.io.net.unixsocket.UnixSockets[IO]
java.lang.NoClassDefFoundError: java/net/UnixDomainSocketAddress
  fs2.io.net.unixsocket.UnixSocketsCompanionPlatform.forAsync(UnixSocketsPlatform.scala:36)
  fs2.io.net.unixsocket.UnixSocketsCompanionPlatform.forAsync$(UnixSocketsPlatform.scala:34)
  fs2.io.net.unixsocket.UnixSockets$.forAsync(UnixSockets.scala:50)
  ammonite.$sess.cmd2$.<clinit>(cmd2.sc:846)
java.lang.ClassNotFoundException: java.net.UnixDomainSocketAddress
  java.net.URLClassLoader.findClass(URLClassLoader.java:435)
  ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:241)
  java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  fs2.io.net.unixsocket.UnixSocketsCompanionPlatform.forAsync(UnixSocketsPlatform.scala:36)
  fs2.io.net.unixsocket.UnixSocketsCompanionPlatform.forAsync$(UnixSocketsPlatform.scala:34)
  fs2.io.net.unixsocket.UnixSockets$.forAsync(UnixSockets.scala:50)
  ammonite.$sess.cmd2$.<clinit>(cmd2.sc:846)
```

The `UnixSockets.forAsync` method is designed to dynamically test whether it's executing on JDK16+. If so, it uses the JDK backend and otherwise it falls back to the JNR backend. When running on Scala 3 however, the `ClassNotFoundException` is thrown when loading the `JdkUnixSockets` class.

The implementation of `JdkUnixSockets` is:

```scala
object JdkUnixSockets {

  def supported: Boolean = StandardProtocolFamily.values.size > 2

  implicit def forAsync[F[_]](implicit F: Async[F]): UnixSockets[F] =
    new UnixSockets.AsyncUnixSockets[F] {
      protected def openChannel(address: UnixSocketAddress) = F.delay {
        val ch = SocketChannel.open(StandardProtocolFamily.UNIX)
        ch.connect(UnixDomainSocketAddress.of(address.path))
        ch
      }

      protected def openServerChannel(address: UnixSocketAddress) = F.blocking {
        val serverChannel = ServerSocketChannel.open(StandardProtocolFamily.UNIX)
        serverChannel.configureBlocking(false)
        serverChannel.bind(UnixDomainSocketAddress.of(address.path))
        (F.blocking(serverChannel.accept()), F.blocking(serverChannel.close()))
      }
    }
}
```

Scala 3 emits much different byte code for this than Scala 2. In particular, the anonymous functions defined inside the anonymous class are emitted by Scala 3 as static methods on the `JdkUnixSockets` object. Scala 2 emitted those anonymous functions as static methods on the anonymous class instead.

This change in strategy results in a static method on `JdkUnixSockets` for each appearance of `F.delay`. And those static methods take `UnixSocketAddress` arguments, resulting in the linkage problem.

To fix, we can simply move the anonymous class to a regular named class. We should do this for both `JdkUnixSockets` and `JnrUnixSockets`.

### PR DESCRIPTION
**Pull request by mpilquist**
Fixes #2623

### CODE REVIEW

**Review by armanbilge — APPROVED** [review]
Do we care enough to add any sort of regression tests?

**Comment by mpilquist** [comment]
I don't know how we could do that. Good news is that http4s build will validate this though.

**Review by ChristopherDavenport — APPROVED** [review]

**Comment by armanbilge** [comment]
Can't we do CI for fs2 on older JDKs? It's only UnixSockets that needs JDK 16 right, and this is specifically what we'd want to test?

**Comment by vasilmkd** [comment]
It complicates the build with two JDKs, one for building, one for running.

**Comment by armanbilge** [comment]
Yeah, now that its being tested downstream probably more trouble than it's worth.

**Comment by mpilquist** [comment]
Yeah, not sure what that build would even look like. If we tried just running the same test suite on a different JDK, then SBT will recompile everything. We'd have to somehow publish artifacts somewhere and then run a completely different SBT project using those artifacts.

**Comment by armanbilge** [comment]
> We'd have to somehow publish artifacts somewhere and then run a completely different SBT project using those artifacts.

Aren't the artifacts already pushed into GHA cache?

**Comment by mpilquist** [comment]
Yes but SBT will notice the JDK changed and invalidate them / rebuild them.

**Review by diesalbla — APPROVED** [review]

**Pull request merged**
