### PR TITLE
Stream / Pull: bypass some uses of `.pull.uncons`.

### PR DESCRIPTION
**Pull request by diesalbla**
This is an attempt to move some of the code that works by `uncons`ing
a stream, to be closer to methods of Pull.

- Add method `cons` to pull, to prefix pull with a chunk.
- Add method `unconsNonEmptyChunk` in Pull.
- Replace uses of `.pull.uncons`, which includes spurious uses of `Pull.map` (just to do noop conversions), by Pull.uncons.

### CODE REVIEW

**Comment by mpilquist** [comment]
I think `unconsNonEmptyChunk` is redundant with `uncons` -- we used to have something like that but the interpreter was changed such that it's impossible to get an empty chunk from `uncons` (IIRC).

I'm not really keen on `Pull.uncons(s)` -- I don't like the built-in operations having more power than stuff users can write, and I'm not sure that exposing `Pull.uncons(s)` publicly is worth the API change. For this type of change, I think we'd need some benchmarks showing it pays off.

**Comment by diesalbla** [comment]
> I think unconsNonEmptyChunk is redundant with uncons -- we used to have something like that but the interpreter was changed such that it's impossible to get an empty chunk from uncons (IIRC).

Hmmm Should we add an assertion to the `Output` constructor, to ensure that any chunk inserted into it is non-empty?

**Comment by mpilquist** [comment]
Sure, I'm pretty sure that's safe, b/c the only way to construct an `Output` checks for empty:

```scala
  def output[F[x] >: Pure[x], O](os: Chunk[O]): Pull[F, O, Unit] =
    if (os.isEmpty) Pull.done else Output[O](os)
```

**Comment by diesalbla** [comment]
ok... incoming PR...

**Pull request closed without merging**
