### PR TITLE
Remove unreachable code

### PR DESCRIPTION
**Pull request by bplommer**

### CODE REVIEW

**Review by SystemFw — APPROVED** [review]

**Comment by SystemFw** [comment]
mm, the CI seems to be stuck

**Comment by bplommer** [comment]
I left some duplicate code in there - maybe pushing a fix for that will unstick the CI 🙂

**Comment by SystemFw** [comment]
So before it got completely stuck I saw an error relating to the work stealing pool being compiled with a different version. @mpilquist rings a bell?

**Comment by bplommer** [comment]
I've run into issues with that previously - the fix for me was to run SBT with JDK 14.

**Comment by mpilquist** [comment]
Yeah I accidentally release CE3 snapshot with JDK14. I'm trying to release with JDK8 but running in to a Sonatype issue and haven't had time to debug.

**Pull request merged**
