### PR TITLE
Fix ipv4 codec

### PR DESCRIPTION
**Pull request by rext**
Thanks for opening a PR!

Target the `main` branch if this PR is targeted for the 3.x series and the `series/2.5.x` branch if targeted for the 2.5.x series.

If the CI build fails due to Scalafmt, run `sbt fmt` and push the changes (generally a good idea to run this prior to opening the PR).

Feel free to ask questions on the fs2 and fs2-dev channels on the [Typelevel Discord server](https://discord.gg/9V8FZTVZ9R).

### CODE REVIEW

**Comment by nikiforo** [comment]
Thanks for the PR!
`If the CI build fails due to Scalafmt, run sbt fmt and push the changes (generally a good idea to run this prior to opening the PR).`

**Comment by mpilquist** [comment]
@rext Thanks for spotting and fixing this. I added support for parsing options at the last minute and clearly didn't test it. :)

**Comment by rext** [comment]
Thank you for merging

**Comment by vasilmkd** [comment]
Thank you for your contribution!

**Pull request merged**
