### PR TITLE
Make Compiler.Target extend MonadCancelThrow

### PR DESCRIPTION
**Pull request by bplommer**
This is intended to facilitate using `Target` as a context bound when you need `MonadCancelThrow` but don't specifically need either `Sync` or `Concurrent`.

### CODE REVIEW

**Comment by kubukoz** [comment]
Personal take, I wish Target didn't extend either of these traits at all... but I guess this avoids the conflict since you can no longer require `Target` and a typeclass with only partial overlap?

**Comment by bplommer** [comment]
> Personal take, I wish Target didn't extend either of these traits at all... 

Why's that?

> but I guess this avoids the conflict since you can no longer require `Target` and a typeclass with only partial overlap?

Yeah - as things stand, if you need both `Target` and `MonadCancelThrow` you either have ambiguous instances of `MonadThrow` or you pick one of `Sync` or `Concurrent` - then if you have dependencies that made both choices you end up using `Async` to satisfy both, when one or the other should have sufficed.

**Comment by kubukoz** [comment]
> Why's that?

Conflicts with other context bounds when you want to use extension methods for a common subset (e.g. `.map`), thus requiring PRs like this one :D

I guess there's a reason why I use `Compiler[F, F]` instead

**Comment by bplommer** [comment]
Linking https://github.com/http4s/http4s/pull/5206 in case anyone wants to weigh in on why the whole idea of using `Target` as a context bound is a bad idea.

**Comment by mpilquist** [comment]
I pushed an additional commit to remove some of the intermediate classes.

**Pull request merged**
