### PR TITLE
Reproducer and fix for race condition in StreamSubscriber

### PR DESCRIPTION
**Pull request by vigoo**
Test case demonstrating https://github.com/typelevel/fs2/issues/2076 and a proposed fix.

### CODE REVIEW

**Review by SystemFw — APPROVED** [review]

**Comment by SystemFw** [comment]
@mpilquist what should we do with the bincompat failures here? Do you think it's enough to eliminate `Runner` as an argument?

**Comment by vigoo** [comment]
Yeah I wanted to ask for advice regarding those. I only introduced that runner parameter to be able to inject the delays in the reproducer test case. I considered only the `fromPublisher` / `toUnicastPublisher` / `toStream` functions part of the public API and those did not change, but I guess I was wrong about that :)

**Comment by SystemFw** [comment]
>  I only introduced that runner parameter to be able to inject the delays in the reproducer test case.

maybe you can provide a custom instance of `ConcurrentEffect` for that purpose instead?

**Comment by vigoo** [comment]
Good idea, let me try

**Comment by vigoo** [comment]
Binary compatibility restored :)

**Pull request merged**
