### PR TITLE
introduce Stream.paginate

### PR DESCRIPTION
**Pull request by yanns**
When consuming resources from an API using pagination, it is usefull to signal at the same time that there are no more elements to read and to emit the last ones read.

For example, when iterating 10 by 10 elements, the last "page" can return 6 elements.
In the case, the `Stream` can emit those 6 elements and stop there, as we know that there are no more elements to read (`6 < 10`)

### CODE REVIEW

**Comment by SystemFw** [comment]
mm, isn't this the same as `unfoldLoop` and `unfoldLoopEval`?

**Comment by yanns** [comment]
@SystemFw yes I oversaw that. Thx!
Should I add the `unfoldLoopChunkEval` version?

```
  def unfoldLoopChunkEval[F[_], S, O](s: S)(f: S => F[(Chunk[O], Option[S])]): Stream[F, O] =
    Stream.unfoldLoopEval(s)(f).flatMap(Stream.chunk)
```

**Comment by SystemFw** [comment]
> Should I add the unfoldLoopChunkEval version?

I'm inclined to say no, because you can then add another version of any combinator, just by adding `flatMap(Stream.chunk)`. I do wish we had a better website structure to allow people to add small docs/tutorials,   even if it's just "hey, if you need pagination use `unfoldLoopEval`"

**Comment by Daenyth** [comment]
A "cookbook" site would be sweet

**Pull request closed without merging**
