### PR TITLE
Readability (+ future performance) improvements

### PR DESCRIPTION
**Pull request by bplommer**
- Remove redundancy/duplication
- Use combinators where appropriate
- Reduce nesting in flatMap chain

### CODE REVIEW

**Comment by Daenyth** [comment]
I'm curious if the changes to use combinators affects the benchmarks at all - do you see a difference with/without them?

**Comment by bplommer** [comment]
> I'm curious if the changes to use combinators affects the benchmarks at all - do you see a difference with/without them?

I haven't run the whole suite, but the `parJoin` benchmark with 256x concurrency seems to be about 2% slower. Maybe it's worth overriding the combinators in the standard CE `Ref` implementation to remove the extra indirection, especially as `Semaphore` now uses them in CE3?

**Comment by bplommer** [comment]
With https://github.com/typelevel/cats-effect/pull/1242, derived methods on `Ref` Are overridden to operate directly on the underlying `AtomicReference`. So the slight performance hit will become a slight boost.

**Comment by mpilquist** [comment]
@bplommer When I merged this forward to develop branch, I lost the changes to `parJoin`, as the implementation on develop is a bit different. In general, let's target develop branch for readability improvements and keep main branch for performance or correctness issues. Thanks!

**Pull request merged**
