### PR TITLE
Add reproduction case of leak with merge+parJoinUnbounded

### PR DESCRIPTION
**Pull request by mpilquist**
Reproduction case for #2598.

Fails on 3.1.1 and 3.0.0 but passes on 2.5.9.

### CODE REVIEW

**Comment by mpilquist** [comment]
Some observations:

- None of these leak:
```scala
Stream(Stream.constant(1).covary[IO]).parJoinUnbounded // NO LEAK
Stream(Stream.constant(1).covary[IO], Stream.constant(1).covary[IO]).parJoinUnbounded // NO LEAK
Stream(Stream(Stream.constant(1).covary[IO]).parJoinUnbounded).parJoinUnbounded // NO LEAK
Stream(Stream.eval(IO(Stream.constant(1))).flatten).parJoinUnbounded // NO LEAK
Stream(Stream(Stream.constant(1).covary[IO], Stream()).parJoinUnbounded).parJoinUnbounded // NO LEAK
```

This does leak:

```scala
Stream(Stream.constant(1).covary[IO].map(Stream(_).onFinalize(IO.unit)).flatten).parJoinUnbounded
```
Whereas removing the finalizer does NOT leak:

```scala
Stream(Stream.constant(1).covary[IO].map(Stream(_)).flatten).parJoinUnbounded // NO LEAK
```

**Comment by diesalbla** [comment]
The following line, which does not involve the parallelism of `parJoinUnbounded`, also causes leak: 
```Scala
    str.chunks.foreach(_ => IO.unit).interruptWhen(IO.never: IO[Either[Throwable, Unit]])
```

**Comment by mpilquist** [comment]
We've been able to further minimize to:

```scala
Stream.constant(1).flatMap(s => Stream(1, 1).flatMap(_ => Stream(s))).chunks
```

**Comment by diesalbla** [comment]
> We've been able to further minimize to:
> 
> ```scala
> Stream.constant(1).flatMap(s => Stream(1, 1).flatMap(_ => Stream(s))).chunks
> ```

This specific case is added and fixed in #2602 . Still looking for the main one, though.

**Comment by diesalbla** [comment]
Closed by #2602

**Pull request closed without merging**
